import { pdvHandoffRedeemRequestSchema } from "@germinatura/contracts";
import { NextResponse } from "next/server";
import { accountUsable, eligiblePdvCohorts, operatesPdvIn, parsePdvCohort, sessionIn, withPdvCohort } from "@/lib/pdv-cohort";
import { createPdvSupabaseAdminClient } from "@/lib/supabase-admin";
import { createPdvSupabaseServerClient } from "@/lib/supabase-server";

const expired = "O acesso pelo Portal expirou. Abra o PDV de novo pelo Portal ou entre com usuário e senha.";

function response(code: string, message: string, status: number) {
  return NextResponse.json({ code, message }, { status, headers: { "Cache-Control": "no-store" } });
}

function trustedOrigin(request: Request): boolean {
  const origin = request.headers.get("origin");
  const configured = process.env.NEXT_PUBLIC_PDV_URL ?? "http://127.0.0.1:3001";
  try {
    return origin !== null && new URL(origin).origin === new URL(configured).origin;
  } catch {
    return false;
  }
}

async function sha256Hex(value: string) {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value));
  return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, "0")).join("");
}

/**
 * Spec 6.1: redeems the single-use Portal code and opens the PDV session on the server, with a magic-link token
 * generated by the service role (no email is sent). The seller role is checked exactly as in the password login.
 */
export async function POST(request: Request) {
  if (!trustedOrigin(request)) return response("INVALID_ORIGIN", "Origem não autorizada", 403);
  const parsed = pdvHandoffRedeemRequestSchema.safeParse(await request.json().catch(() => null));
  if (!parsed.success) return response("PDV_HANDOFF_INVALID", expired, 401);
  try {
    const admin = createPdvSupabaseAdminClient();
    const { data: redeemed, error: redeemError } = await admin.rpc("consume_pdv_handoff", { p_code_hash: await sha256Hex(parsed.data.code) });
    if (redeemError?.message.includes("PDV_HANDOFF_INVALID")) return response("PDV_HANDOFF_INVALID", expired, 401);
    const email = (redeemed as { email?: unknown } | null)?.email;
    if (redeemError || typeof email !== "string") throw new Error("PDV_HANDOFF_UNAVAILABLE");

    const { data: link, error: linkError } = await admin.auth.admin.generateLink({ type: "magiclink", email });
    const tokenHash = link?.properties?.hashed_token;
    if (linkError || !tokenHash) throw new Error("PDV_HANDOFF_UNAVAILABLE");
    const client = await createPdvSupabaseServerClient();
    const { error: verifyError } = await client.auth.verifyOtp({ type: "magiclink", token_hash: tokenHash });
    if (verifyError) throw new Error("PDV_HANDOFF_UNAVAILABLE");

    // ADR 0011: the cohort comes from the code stored by the Portal, never from the URL, and the database confirms the
    // PDV role inside it. A code issued before cohorts (none stored) follows the same rule as the password login.
    const handoffCohort = parsePdvCohort(typeof (redeemed as { cohort_id?: unknown }).cohort_id === "string"
      ? (redeemed as { cohort_id: string }).cohort_id : null);
    let cohort: string | null = null;
    if (handoffCohort) {
      const { session } = await sessionIn(client, handoffCohort);
      cohort = operatesPdvIn(session, handoffCohort) ? handoffCohort : null;
      if (!cohort) {
        await client.auth.signOut();
        return response("FORBIDDEN", "Sua conta não tem acesso ao PDV nesta turma.", 403);
      }
    } else {
      const { session } = await sessionIn(client, null);
      const eligible = accountUsable(session) ? await eligiblePdvCohorts(client, session) : [];
      if (eligible.length === 0) {
        await client.auth.signOut();
        return response("FORBIDDEN", "Sua conta não tem acesso ao PDV.", 403);
      }
      cohort = eligible.length === 1 ? eligible[0]!.id : null;
    }
    // AUD-001: best effort; recording a login never changes its outcome.
    await client.rpc("record_login_success", { p_app: "PDV", p_request_id: null }).then(() => undefined, () => undefined);
    return withPdvCohort(NextResponse.json({ ok: true }, { headers: { "Cache-Control": "no-store" } }), cohort);
  } catch {
    return response("AUTH_UNAVAILABLE", "Autenticação temporariamente indisponível", 503);
  }
}
