begin;
select plan(33);

select has_table('public', 'stock_locations', 'stock locations table exists');
select has_table('public', 'inventory_balances', 'inventory balances table exists');
select has_type('public', 'stock_location_type', 'stock location type exists');
select col_type_is('public', 'inventory_balances', 'on_hand_quantity', 'bigint', 'on-hand quantity uses bigint');
select col_type_is('public', 'inventory_balances', 'reserved_quantity', 'bigint', 'reserved quantity uses bigint');
select ok(
  (select is_generated = 'ALWAYS' from information_schema.columns where table_schema = 'public' and table_name = 'inventory_balances' and column_name = 'available_quantity'),
  'available quantity is generated by the database'
);
select results_eq(
  $$select count(*)::bigint from pg_class where oid in ('public.stock_locations'::regclass, 'public.inventory_balances'::regclass) and relrowsecurity$$,
  array[2::bigint],
  'all inventory foundation tables have RLS enabled'
);
select results_eq(
  $$select count(*)::bigint from pg_policies where schemaname = 'public' and tablename in ('stock_locations', 'inventory_balances') and cmd in ('INSERT', 'UPDATE', 'DELETE')$$,
  array[0::bigint],
  'inventory foundation has no direct write policies'
);
select results_eq(
  $$select count(*)::bigint from information_schema.role_table_grants where table_schema = 'public' and table_name in ('stock_locations', 'inventory_balances') and grantee in ('anon', 'authenticated') and privilege_type <> 'SELECT'$$,
  array[0::bigint],
  'API roles receive no inventory write grants'
);
select results_eq(
  $$select count(*)::bigint from information_schema.role_table_grants where table_schema = 'public' and table_name in ('stock_locations', 'inventory_balances') and grantee = 'anon'$$,
  array[0::bigint],
  'anonymous users receive no inventory grants'
);
select results_eq(
  $$select count(*)::bigint from information_schema.role_table_grants where table_schema = 'public' and table_name in ('stock_locations', 'inventory_balances') and grantee = 'service_role'$$,
  array[0::bigint],
  'service role receives no direct inventory grants'
);
select results_eq(
  $$select count(*)::bigint from public.stock_locations where location_type = 'CENTRAL' and active$$,
  array[1::bigint],
  'seed creates one active central location'
);
select results_eq(
  $$select count(*)::bigint from public.stock_locations where location_type = 'SELLER' and seller_id = '10000000-0000-4000-8000-000000000002'$$,
  array[1::bigint],
  'seed creates the local seller location'
);

select throws_ok(
  $$insert into public.stock_locations (location_type, name) values ('CENTRAL', 'Outra central')$$,
  '23505', null, 'a second active central location is rejected'
);
select throws_ok(
  $$insert into public.stock_locations (location_type, name, seller_id) values ('SELLER', 'Duplicada', '10000000-0000-4000-8000-000000000002')$$,
  '23505', null, 'a seller cannot receive a second location'
);
select throws_ok(
  $$insert into public.stock_locations (location_type, name) values ('SELLER', 'Sem vendedor')$$,
  '23514', null, 'seller location requires an owner'
);
select throws_ok(
  $$insert into public.stock_locations (location_type, name, seller_id) values ('CENTRAL', 'Central inválida', '10000000-0000-4000-8000-000000000003')$$,
  '23514', null, 'central location cannot have a seller owner'
);

insert into public.categories (id, name, slug) values
  ('21000000-0000-4000-8000-000000000001', 'Inventário', 'inventario');
insert into public.products (id, category_id, sku, slug, name, active, published) values
  ('31000000-0000-4000-8000-000000000001', '21000000-0000-4000-8000-000000000001', 'ITEM-ESTOQUE', 'item-estoque', 'Item de estoque', true, true);
insert into public.inventory_balances (location_id, product_id, on_hand_quantity, reserved_quantity) values
  ('50000000-0000-4000-8000-000000000001', '31000000-0000-4000-8000-000000000001', 20, 2),
  ('50000000-0000-4000-8000-000000000002', '31000000-0000-4000-8000-000000000001', 10, 3);

select results_eq(
  $$select available_quantity from public.inventory_balances where location_id = '50000000-0000-4000-8000-000000000002'$$,
  array[7::bigint],
  'available quantity is derived from physical minus reserved'
);
select throws_ok(
  $$insert into public.inventory_balances (location_id, product_id, on_hand_quantity) values ('50000000-0000-4000-8000-000000000001', '31000000-0000-4000-8000-000000000001', 1)$$,
  '23505', null, 'a product has one balance per location'
);
select throws_ok(
  $$update public.inventory_balances set on_hand_quantity = -1 where location_id = '50000000-0000-4000-8000-000000000001'$$,
  '23514', null, 'negative physical quantity is rejected'
);
select throws_ok(
  $$update public.inventory_balances set reserved_quantity = -1 where location_id = '50000000-0000-4000-8000-000000000001'$$,
  '23514', null, 'negative reserved quantity is rejected'
);
select throws_ok(
  $$update public.inventory_balances set reserved_quantity = 21 where location_id = '50000000-0000-4000-8000-000000000001'$$,
  '23514', null, 'reserved quantity cannot exceed physical quantity'
);

set local role anon;
select throws_ok($$select * from public.stock_locations$$, '42501', null, 'anonymous inventory reads are denied');
reset role;

set local role authenticated;
set local "request.jwt.claim.sub" = '10000000-0000-4000-8000-000000000003';
select results_eq($$select count(*)::bigint from public.stock_locations$$, array[0::bigint], 'consumer sees no stock location');
select results_eq($$select count(*)::bigint from public.inventory_balances$$, array[0::bigint], 'consumer sees no inventory balance');
reset role;

set local role authenticated;
set local "request.jwt.claim.sub" = '10000000-0000-4000-8000-000000000002';
select results_eq(
  $$select array_agg(location_type::text order by location_type::text) from public.stock_locations$$,
  $$values (array['SELLER'::text])$$,
  'seller sees only their own virtual location'
);
select results_eq(
  $$select array_agg(available_quantity order by available_quantity) from public.inventory_balances$$,
  $$values (array[7::bigint])$$,
  'seller sees only their own balance'
);
select throws_ok(
  $$update public.inventory_balances set on_hand_quantity = 9$$,
  '42501', null, 'seller cannot mutate their balance directly'
);
reset role;

set local role authenticated;
set local "request.jwt.claim.sub" = '10000000-0000-4000-8000-000000000001';
select results_eq($$select count(*)::bigint from public.stock_locations$$, array[2::bigint], 'inventory manager sees every location');
select results_eq($$select count(*)::bigint from public.inventory_balances$$, array[4::bigint], 'inventory manager sees every seeded balance');
select throws_ok(
  $$insert into public.inventory_balances (location_id, product_id) values ('50000000-0000-4000-8000-000000000001', '31000000-0000-4000-8000-000000000001')$$,
  '42501', null, 'inventory manager cannot write balances directly'
);
reset role;

select throws_ok(
  $$delete from public.inventory_balances where location_id = '50000000-0000-4000-8000-000000000001'$$,
  'P0001', 'INVENTORY_HARD_DELETE_FORBIDDEN', 'balances cannot be hard deleted'
);
select throws_ok(
  $$delete from public.stock_locations where id = '50000000-0000-4000-8000-000000000001'$$,
  'P0001', 'INVENTORY_HARD_DELETE_FORBIDDEN', 'locations cannot be hard deleted'
);

select * from finish();
rollback;
