import { idempotencyKeySchema, inventoryCountMutationResponseSchema, inventoryCountQuerySchema, submitInventoryCountSchema } from "@germinatura/contracts";
import { createRequestId } from "@germinatura/observability";
import { NextResponse } from "next/server";
import { AuthorizationError, requirePermission } from "@/lib/auth";
import { createAuthenticatedSupabaseClient } from "@/lib/authenticated-supabase";
import { countError, countFail, countHeaders, mapCountContext } from "./helpers";

export async function GET(request: Request) {
  const requestId=createRequestId(request.headers); try { await requirePermission("inventory.count.own"); const parsed=inventoryCountQuerySchema.safeParse(Object.fromEntries(new URL(request.url).searchParams)); if(!parsed.success)return countFail(requestId,"INVALID_COUNT_QUERY","Consulta de inventário inválida.",422); const client=await createAuthenticatedSupabaseClient(request); const{data,error}=await client.rpc("get_inventory_count_context",{p_location_id:parsed.data.locationId??null,p_cursor:parsed.data.cursor??null,p_limit:parsed.data.limit}); if(error)return countError(requestId,error); const result=mapCountContext(data,requestId); if(!result.success)return countFail(requestId,"INVENTORY_UNAVAILABLE","A consulta retornou dados inválidos.",503); return NextResponse.json(result.data,{headers:countHeaders(requestId)}); } catch(error){if(error instanceof AuthorizationError)return countFail(requestId,error.status===401?"UNAUTHENTICATED":"FORBIDDEN",error.message,error.status);return countFail(requestId,"INVENTORY_UNAVAILABLE","Não foi possível carregar o inventário.",503);}
}

export async function POST(request: Request) {
  const requestId=createRequestId(request.headers); try { await requirePermission("inventory.count.own"); const key=idempotencyKeySchema.safeParse(request.headers.get("idempotency-key")); const parsed=submitInventoryCountSchema.safeParse(await request.json().catch(()=>null)); if(!key.success||!parsed.success)return countFail(requestId,"INVALID_INVENTORY_COUNT","Confira as quantidades e a justificativa.",422); const client=await createAuthenticatedSupabaseClient(request); const correlationId=crypto.randomUUID(); const{data,error}=await client.rpc("submit_inventory_count",{p_location_id:parsed.data.locationId??null,p_items:parsed.data.items.map((item)=>({product_id:item.productId,expected_on_hand_quantity:item.expectedOnHandQuantity,expected_reserved_quantity:item.expectedReservedQuantity,counted_on_hand_quantity:item.countedOnHandQuantity})),p_observation:parsed.data.observation,p_idempotency_key:key.data,p_correlation_id:correlationId}); if(error)return countError(requestId,error); const result=inventoryCountMutationResponseSchema.safeParse({data:{countId:data?.count_id,status:data?.status,correlationId:data?.correlation_id},request_id:requestId}); if(!result.success)return countFail(requestId,"INVENTORY_UNAVAILABLE","Não foi possível confirmar a contagem.",503); return NextResponse.json(result.data,{status:201,headers:countHeaders(requestId)}); } catch(error){if(error instanceof AuthorizationError)return countFail(requestId,error.status===401?"UNAUTHENTICATED":"FORBIDDEN",error.message,error.status);return countFail(requestId,"INVENTORY_UNAVAILABLE","Não foi possível registrar a contagem.",503);}
}
