import { expect, test } from "@playwright/test";

const portal="http://127.0.0.1:3000";const endpoint=`${portal}/api/v1/admin/promotions`;const headers={Origin:portal,"Sec-Fetch-Site":"same-origin"};

test("administra promoção por quantidade com histórico e bloqueia papel indevido",async({page,browser},testInfo)=>{
  test.slow();expect((await page.request.post(`${portal}/api/auth/login`,{headers,data:{identifier:"admin.teste",password:"Admin123!"}})).status()).toBe(200);await page.setViewportSize({width:390,height:844});await page.goto(`${portal}/admin/promocoes`);await expect(page.getByRole("heading",{name:"Promoções por quantidade"})).toBeVisible();
  const code=`E2E-${crypto.randomUUID()}`.toUpperCase();await page.getByLabel("Código").fill(code);await page.getByLabel("Nome").fill("Duas unidades em oferta");await page.getByLabel("Preço do grupo (R$)").fill("10,00");await page.getByLabel(/Item público A/).check();await page.getByLabel("Motivo").fill("Criar promoção para teste operacional");
  const createResponse=page.waitForResponse((response)=>response.url()===endpoint&&response.request().method()==="POST");await page.getByRole("button",{name:"Salvar promoção"}).click();const created=await createResponse;expect(created.status()).toBe(201);const result=await created.json() as{data:{id:string;revision:number}};await expect(page.getByRole("status")).toContainText("Promoção salva");const row=page.getByRole("listitem").filter({hasText:code});await expect(row).toContainText("Inativa");await row.getByRole("button",{name:"Editar"}).click();await page.getByLabel("Nome").fill("Três unidades em oferta");await page.getByLabel("Quantidade do grupo").fill("3");await page.getByLabel("Preço do grupo (R$)").fill("12,00");await page.getByLabel("Motivo").fill("Atualizar regra durante teste operacional");
  const updateResponse=page.waitForResponse((response)=>response.url()===endpoint&&response.request().method()==="POST");await page.getByRole("button",{name:"Salvar promoção"}).click();expect((await updateResponse).status()).toBe(200);await expect(page.getByRole("listitem").filter({hasText:code})).toContainText("3 por");
  const stale={id:result.data.id,expectedRevision:result.data.revision,code,name:"Edição antiga",description:null,active:false,publicable:false,priority:0,cumulative:false,validFrom:new Date().toISOString(),validTo:null,globalRedemptionLimit:null,perUserRedemptionLimit:null,productIds:["33f00000-0000-4000-8000-000000000001"],channels:["PDV"],rule:{type:"QUANTIDADE_PRECO",groupQuantity:2,groupPriceCents:1000,maxGroupsPerLine:null},reason:"Tentar edição antiga"};
  const conflict=await page.request.post(endpoint,{headers:{...headers,"Idempotency-Key":`promotion-stale:${crypto.randomUUID()}`},data:stale});expect(conflict.status()).toBe(409);expect((await conflict.json() as{code:string}).code).toBe("PROMOTION_REVISION_CONFLICT");expect((await page.request.post(endpoint,{headers:{Origin:"https://untrusted.invalid","Idempotency-Key":"promotion-origin"},data:stale})).status()).toBe(403);expect((await page.request.post(endpoint,{headers:{...headers,"Idempotency-Key":"promotion-unknown"},data:{...stale,totalCents:1}})).status()).toBe(422);await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:testInfo.outputPath("promotion-mobile.png"),fullPage:true});
  const consumer=await browser.newContext();try{expect((await consumer.request.post(`${portal}/api/auth/login`,{headers,data:{identifier:"consumidor.teste",password:"Consumidor123!"}})).status()).toBe(200);expect((await consumer.request.post(endpoint,{headers:{...headers,"Idempotency-Key":"promotion-consumer"},data:stale})).status()).toBe(403);const consumerPage=await consumer.newPage();await consumerPage.goto(`${portal}/admin/promocoes`);await expect(consumerPage).toHaveURL(`${portal}/`);}finally{await consumer.close();}
});
