"use client";

import { Badge, Button, Card, Field, Input } from "@germinatura/ui";
import type { InventoryCountContextResponse } from "@germinatura/contracts";
import { ArrowLeftRight, ClipboardCheck, PackageCheck, RefreshCw, RotateCcw, Scale, TriangleAlert, X } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { cancelInventoryCount, loadInventoryCounts, submitInventoryCount } from "@/lib/operations";
import { useToast } from "@/components/ui/Toast";

type Context = InventoryCountContextResponse["data"];
type Count = Context["counts"][number];
const labels:Record<Count["status"],string>={PENDING_APPROVAL:"Aguardando aprovação",APPLIED:"Aplicada",REJECTED:"Recusada",CANCELLED:"Cancelada"};
const movementLabels:Record<string,string>={SALDO_INICIAL:"Saldo inicial",ENTRADA_COMPRA:"Entrada",TRANSFERENCIA:"Transferência",VENDA:"Venda",RESERVA:"Reserva",LIBERACAO_RESERVA:"Liberação",PERDA:"Perda",VENCIMENTO:"Vencimento",DEVOLUCAO:"Devolução",AJUSTE_POSITIVO:"Ajuste positivo",AJUSTE_NEGATIVO:"Ajuste negativo",CANCELAMENTO_VENDA:"Cancelamento"};
const key=(prefix:string)=>`${prefix}:${crypto.randomUUID()}`;
const messageFrom=(cause:unknown)=>cause instanceof Error?cause.message:"Não foi possível concluir esta ação.";

export function MyStockWorkspace({online,onNavigate}:{online:boolean;onNavigate:(view:"transfers"|"returns"|"losses")=>void}){
  const[context,setContext]=useState<Context|null>(null);const[counts,setCounts]=useState<Record<string,string>>({});const[observation,setObservation]=useState("");const[cancelReasons,setCancelReasons]=useState<Record<string,string>>({});const[loading,setLoading]=useState(true);const[action,setAction]=useState<string|null>(null);const[error,setError]=useState("");const submitKey=useRef(key("inventory-count"));const cancelKeys=useRef(new Map<string,string>());const{showToast}=useToast();
  const load=useCallback(async(cursor?:string)=>loadInventoryCounts(cursor),[]);
  const refresh=useCallback(async()=>{setLoading(true);setError("");try{const next=await load();setContext(next);setCounts(Object.fromEntries(next.balances.map((item)=>[item.productId,String(item.onHandQuantity)])));}catch(cause){setError(messageFrom(cause));}finally{setLoading(false);}},[load]);
  useEffect(()=>{const timer=window.setTimeout(()=>void refresh(),0);return()=>window.clearTimeout(timer);},[refresh]);
  async function submit(event:React.FormEvent){event.preventDefault();if(!context||!online||observation.trim().length<4)return;const items=context.balances.map((item)=>({productId:item.productId,expectedOnHandQuantity:item.onHandQuantity,expectedReservedQuantity:item.reservedQuantity,countedOnHandQuantity:Number(counts[item.productId])}));if(!items.length||items.some((item)=>!Number.isSafeInteger(item.countedOnHandQuantity)||item.countedOnHandQuantity<0))return;setAction("submit");setError("");try{await submitInventoryCount({locationId:context.selectedLocationId,observation:observation.trim(),items},submitKey.current);submitKey.current=key("inventory-count");setObservation("");showToast("Contagem enviada para confirmação.","success");await refresh();}catch(cause){setError(messageFrom(cause));}finally{setAction(null);}}
  async function cancel(item:Count){const reason=cancelReasons[item.id]?.trim()??"";if(reason.length<4)return;const operation=`cancel:${item.id}`;const idempotency=cancelKeys.current.get(item.id)??key("inventory-count-cancel");cancelKeys.current.set(item.id,idempotency);setAction(operation);try{await cancelInventoryCount(item.id,reason,idempotency);cancelKeys.current.delete(item.id);showToast("Contagem cancelada.","success");await refresh();}catch(cause){setError(messageFrom(cause));}finally{setAction(null);}}
  async function older(){if(!context?.nextCursor||action)return;setAction("older");try{const page=await load(context.nextCursor);setContext((current)=>current?{...current,nextCursor:page.nextCursor,counts:[...current.counts,...page.counts.filter((item)=>!current.counts.some((known)=>known.id===item.id))]}:page);}catch(cause){setError(messageFrom(cause));}finally{setAction(null);}}
  if(loading&&!context)return <Card className="p-6"><p role="status">Carregando meu estoque…</p></Card>;
  return <div className="space-y-6"><div className="grid gap-3 sm:grid-cols-3"><Button type="button" variant="secondary" onClick={()=>onNavigate("transfers")}><ArrowLeftRight className="size-4"/> Transferir</Button><Button type="button" variant="secondary" onClick={()=>onNavigate("returns")}><RotateCcw className="size-4"/> Devolver</Button><Button type="button" variant="secondary" onClick={()=>onNavigate("losses")}><TriangleAlert className="size-4"/> Registrar perda</Button></div>
    {error&&<p role="alert" className="rounded-lg bg-[var(--g-status-danger-soft)] p-3 text-sm text-[var(--g-status-danger-foreground)]">{error}</p>}
    <section aria-label="Saldos do meu estoque"><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold">Saldos por produto</h2><Button type="button" size="sm" variant="ghost" onClick={()=>void refresh()} disabled={loading||Boolean(action)}><RefreshCw className={`size-4 ${loading?"animate-spin":""}`}/> Atualizar</Button></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{!context?.balances.length?<Card className="p-5 text-sm">Nenhum produto neste estoque.</Card>:context.balances.map((item)=><Card key={item.productId} className="p-5"><p className="font-semibold">{item.productName}</p><p className="mt-1 text-xs text-[var(--g-text-muted)]">{item.productSku}</p><dl className="mt-4 grid grid-cols-3 gap-2 text-sm"><div><dt className="text-xs text-[var(--g-text-muted)]">Físico</dt><dd className="mt-1 font-bold tabular-nums">{item.onHandQuantity}</dd></div><div><dt className="text-xs text-[var(--g-text-muted)]">Reservado</dt><dd className="mt-1 font-bold tabular-nums">{item.reservedQuantity}</dd></div><div><dt className="text-xs text-[var(--g-text-muted)]">Disponível</dt><dd className="mt-1 font-bold tabular-nums">{item.availableQuantity}</dd></div></dl></Card>)}</div></section>
    <Card className="p-5"><div className="flex items-start gap-3"><ClipboardCheck className="mt-0.5 size-5 text-[var(--g-operation-primary)]"/><div><h2 className="font-semibold">Contar meu estoque</h2><p className="mt-1 text-sm text-[var(--g-text-secondary)]">Informe o total físico. A gestão confirma qualquer ajuste depois.</p></div></div><form aria-label="Contar meu estoque" className="mt-5 space-y-4" onSubmit={submit}><div className="grid gap-3 sm:grid-cols-2">{context?.balances.map((item)=><Field key={item.productId} id={`count-${item.productId}`} label={item.productName} description={`Esperado ${item.onHandQuantity}; reservado ${item.reservedQuantity}.`}><Input id={`count-${item.productId}`} type="number" min={0} value={counts[item.productId]??""} onChange={(event)=>{setCounts((current)=>({...current,[item.productId]:event.target.value}));submitKey.current=key("inventory-count");}} disabled={!online||Boolean(action)}/></Field>)}</div><Field id="count-observation" label="Observação"><Input id="count-observation" minLength={4} maxLength={500} value={observation} onChange={(event)=>{setObservation(event.target.value);submitKey.current=key("inventory-count");}} disabled={!online||Boolean(action)}/></Field><Button type="submit" variant="operation" loading={action==="submit"} disabled={!online||!context?.balances.length||observation.trim().length<4||Boolean(action)}><Scale className="size-4"/> Enviar contagem</Button>{!online&&<p role="status" className="text-sm font-semibold">Conecte-se para enviar a contagem.</p>}</form></Card>
    <section aria-label="Minhas contagens"><h2 className="mb-3 font-semibold">Minhas contagens</h2><div className="space-y-3">{!context?.counts.length?<Card className="p-5 text-sm">Nenhuma contagem registrada.</Card>:context.counts.map((item)=><Card key={item.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{item.locationName}</p><p className="mt-1 text-sm text-[var(--g-text-secondary)]">{item.observation}</p></div><Badge tone={item.status==="APPLIED"?"success":item.status==="PENDING_APPROVAL"?"warning":"neutral"}>{labels[item.status]}</Badge></div><ul className="mt-3 space-y-1 text-sm">{item.items.map((entry)=><li key={entry.productId}>{entry.productName}: {entry.expectedOnHandQuantity} → {entry.countedOnHandQuantity} <span className="text-[var(--g-text-muted)]">({entry.differenceQuantity>0?"+":""}{entry.differenceQuantity})</span></li>)}</ul>{item.decisionReason&&<p className="mt-2 text-sm"><span className="text-[var(--g-text-muted)]">Decisão:</span> {item.decisionReason}</p>}{item.status==="PENDING_APPROVAL"&&<div className="mt-4 border-t pt-4"><label htmlFor={`count-cancel-${item.id}`} className="text-sm font-semibold">Motivo do cancelamento</label><Input id={`count-cancel-${item.id}`} className="mt-2" minLength={4} maxLength={500} value={cancelReasons[item.id]??""} onChange={(event)=>setCancelReasons((current)=>({...current,[item.id]:event.target.value}))} disabled={!online||Boolean(action)}/><Button type="button" size="sm" variant="secondary" className="mt-3" onClick={()=>void cancel(item)} loading={action===`cancel:${item.id}`} disabled={!online||(cancelReasons[item.id]?.trim().length??0)<4||Boolean(action)}><X className="size-4"/> Cancelar contagem</Button></div>}</Card>)}{context?.nextCursor&&<Button type="button" variant="secondary" className="w-full" onClick={()=>void older()} loading={action==="older"}>Carregar anteriores</Button>}</div></section>
    <section aria-label="Movimentos recentes"><h2 className="mb-3 font-semibold">Últimas movimentações</h2><div className="space-y-3">{!context?.movements.length?<Card className="p-5 text-sm">Nenhuma movimentação registrada.</Card>:context.movements.map((movement)=><Card key={movement.id} className="p-4"><div className="flex items-center justify-between gap-3"><Badge tone={movement.movementType.includes("NEGATIVO")||["PERDA","VENDA"].includes(movement.movementType)?"danger":"info"}>{movementLabels[movement.movementType]??movement.movementType}</Badge><span className="text-xs text-[var(--g-text-muted)]">{new Date(movement.createdAt).toLocaleString("pt-BR")}</span></div><p className="mt-2 text-sm font-semibold"><PackageCheck className="mr-1 inline size-4"/>{movement.items.map((item)=>`${item.productName}: ${item.quantity}`).join(", ")}</p><p className="mt-1 text-xs text-[var(--g-text-muted)]">{movement.reason}</p></Card>)}</div></section>
  </div>;
}
