"use client";

import { inventoryLotsResponseSchema, type InventoryLotsResponse } from "@germinatura/contracts";
import { Badge, Button, Card, Input } from "@germinatura/ui";
import { History, Search } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

type Position=InventoryLotsResponse["data"][number];
const money=(value:number|null)=>value===null?"Custo não informado":new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value/100);
const movement:Record<string,string>={ENTRADA_COMPRA:"Entrada de compra",TRANSFERENCIA:"Transferência",VENDA:"Venda",PERDA:"Perda",VENCIMENTO:"Vencimento",AJUSTE_POSITIVO:"Ajuste positivo",AJUSTE_NEGATIVO:"Ajuste negativo",CANCELAMENTO_VENDA:"Cancelamento de venda"};
async function requestLots(params:URLSearchParams){const response=await fetch(`/api/v1/admin/inventory/lots?${params}`,{credentials:"include",cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(typeof body?.message==="string"?body.message:"Não foi possível consultar os lotes.");return inventoryLotsResponseSchema.parse(body);}

export function InventoryLotTraceability(){const[data,setData]=useState<Position[]>([]);const[history,setHistory]=useState<InventoryLotsResponse["history"]>([]);const[selected,setSelected]=useState<Position|null>(null);const[query,setQuery]=useState("");const[activeQuery,setActiveQuery]=useState("");const[positionCursor,setPositionCursor]=useState<string|null>(null);const[historyCursor,setHistoryCursor]=useState<string|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
  const search=useCallback(async(value="")=>{setLoading(true);setError("");try{const params=new URLSearchParams();if(value.trim())params.set("query",value.trim());const result=await requestLots(params);setData(result.data);setActiveQuery(value.trim());setPositionCursor(result.nextPositionCursor);setSelected(null);setHistory([]);setHistoryCursor(null);}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível consultar os lotes.");}finally{setLoading(false);}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void search(),0);return()=>window.clearTimeout(timer);},[search]);
  async function inspect(item:Position){setLoading(true);setError("");try{const result=await requestLots(new URLSearchParams({lotId:item.lotId}));setSelected(item);setHistory(result.history);setHistoryCursor(result.nextHistoryCursor);}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível consultar o histórico.");}finally{setLoading(false);}}
  async function older(){if(!selected||!historyCursor)return;setLoading(true);try{const result=await requestLots(new URLSearchParams({lotId:selected.lotId,historyCursor}));setHistory(current=>[...current,...result.history]);setHistoryCursor(result.nextHistoryCursor);}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível consultar o histórico.");}finally{setLoading(false);}}
  async function morePositions(){if(!positionCursor)return;setLoading(true);try{const params=new URLSearchParams({positionCursor});if(activeQuery)params.set("query",activeQuery);const result=await requestLots(params);setData(current=>[...current,...result.data]);setPositionCursor(result.nextPositionCursor);}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível carregar mais lotes.");}finally{setLoading(false);}}
  return <div className="space-y-6"><Card className="p-5"><form className="flex flex-col gap-3 sm:flex-row" onSubmit={event=>{event.preventDefault();void search(query);}}><label className="flex-1"><span className="sr-only">Buscar lote</span><Input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Lote, produto, SKU ou localização" maxLength={100}/></label><Button type="submit" loading={loading}><Search className="size-4"/> Buscar</Button></form>{error&&<p role="alert" className="mt-3 text-sm text-[var(--g-status-danger-foreground)]">{error}</p>}</Card>
    <section aria-label="Posições por lote"><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-bold">Posição atual</h2><span className="text-sm text-[var(--g-text-muted)]">{data.length} registros</span></div>{!loading&&!data.length?<Card className="p-8 text-center text-sm">Nenhum lote encontrado.</Card>:<div className="grid gap-4 lg:grid-cols-2">{data.map(item=><Card key={`${item.lotId}-${item.locationId}`} className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-bold">{item.productName}</p><p className="mt-1 text-sm text-[var(--g-text-muted)]">{item.productSku} · lote {item.lotCode}</p></div><Badge tone={item.onHandQuantity>0?"success":"neutral"}>{item.onHandQuantity} unidade(s)</Badge></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-[var(--g-text-muted)]">Localização</dt><dd className="font-semibold">{item.locationName}</dd></div><div><dt className="text-[var(--g-text-muted)]">Validade</dt><dd className="font-semibold">{item.expiresOn?new Date(`${item.expiresOn}T12:00:00`).toLocaleDateString("pt-BR"):"Não controlada"}</dd></div><div><dt className="text-[var(--g-text-muted)]">Custo de origem</dt><dd className="font-semibold">{money(item.totalCostCents)}</dd></div><div><dt className="text-[var(--g-text-muted)]">Custo consumido</dt><dd className="font-semibold">{money(item.consumedCostCents)}</dd></div></dl><Button type="button" variant="secondary" size="sm" className="mt-4" onClick={()=>void inspect(item)} disabled={loading}><History className="size-4"/> Ver histórico</Button></Card>)}</div>}{positionCursor&&<Button type="button" variant="secondary" className="mt-4 w-full" onClick={()=>void morePositions()} loading={loading}>Carregar mais lotes</Button>}</section>
    {selected&&<Card className="overflow-hidden"><div className="border-b p-5"><h2 className="text-lg font-bold">Histórico do lote {selected.lotCode}</h2><p className="mt-1 text-sm text-[var(--g-text-secondary)]">{selected.productName} · {selected.productSku}</p></div><div className="divide-y">{history.map(item=><article key={item.id} className="p-5"><div className="flex flex-wrap items-center justify-between gap-2"><Badge tone={item.movementType==="VENDA"||item.movementType==="PERDA"?"danger":"info"}>{movement[item.movementType]??item.movementType}</Badge><span className="text-xs text-[var(--g-text-muted)]">{new Date(item.createdAt).toLocaleString("pt-BR")}</span></div><p className="mt-2 font-semibold">{item.quantity} unidade(s) · {money(item.allocatedCostCents)}</p><p className="mt-1 text-sm text-[var(--g-text-secondary)]">{item.reason}</p>{item.sourceType&&<p className="mt-1 break-all text-xs text-[var(--g-text-muted)]">Origem: {item.sourceType} · {item.sourceId}</p>}</article>)}{!history.length&&<p className="p-5 text-sm">Nenhum movimento encontrado.</p>}</div>{historyCursor&&<div className="border-t p-4"><Button type="button" variant="secondary" className="w-full" onClick={()=>void older()} loading={loading}>Carregar anteriores</Button></div>}</Card>}
  </div>;
}
