"use client";

import { inventoryCountContextResponseSchema, inventoryCountMutationResponseSchema, type InventoryCountContextResponse } from "@germinatura/contracts";
import { Badge, Button, Card, Field, Input } from "@germinatura/ui";
import { Check, ClipboardCheck, Loader2, RefreshCw, X } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { useToast } from "@/components/ui/Toast";

type Context=InventoryCountContextResponse["data"];type Count=Context["counts"][number];
const labels:Record<Count["status"],string>={PENDING_APPROVAL:"Aguardando aprovação",APPLIED:"Aplicada",REJECTED:"Recusada",CANCELLED:"Cancelada"};
const key=(prefix:string)=>`${prefix}:${crypto.randomUUID()}`;const messageFrom=(cause:unknown)=>cause instanceof Error?cause.message:"Não foi possível concluir esta ação.";
async function responseMessage(response:Response){const body:unknown=await response.json().catch(()=>null);return typeof body==="object"&&body!==null&&"message"in body&&typeof body.message==="string"?body.message:"Não foi possível concluir esta ação.";}

export function InventoryCountManagement(){
  const[context,setContext]=useState<Context|null>(null);const[locationId,setLocationId]=useState("");const[values,setValues]=useState<Record<string,string>>({});const[observation,setObservation]=useState("");const[decisionReasons,setDecisionReasons]=useState<Record<string,string>>({});const[loading,setLoading]=useState(true);const[action,setAction]=useState<string|null>(null);const[error,setError]=useState("");const submitKey=useRef(key("admin-inventory-count"));const decisionKeys=useRef(new Map<string,string>());const{showToast}=useToast();
  const load=useCallback(async(selected?:string,cursor?:string)=>{const query=new URLSearchParams({limit:"20"});if(selected)query.set("locationId",selected);if(cursor)query.set("cursor",cursor);const response=await fetch(`/api/v1/inventory/counts?${query}`,{cache:"no-store"});if(!response.ok)throw new Error(await responseMessage(response));const parsed=inventoryCountContextResponseSchema.safeParse(await response.json());if(!parsed.success)throw new Error("A consulta retornou dados inválidos.");return parsed.data.data;},[]);
  const refresh=useCallback(async(selected?:string)=>{setLoading(true);setError("");try{const next=await load(selected||locationId||undefined);setContext(next);setLocationId(next.selectedLocationId);setValues(Object.fromEntries(next.balances.map((item)=>[item.productId,String(item.onHandQuantity)])));}catch(cause){setError(messageFrom(cause));}finally{setLoading(false);}},[load,locationId]);
  useEffect(()=>{const timer=window.setTimeout(()=>void refresh(),0);return()=>window.clearTimeout(timer);},[]); // eslint-disable-line react-hooks/exhaustive-deps
  async function changeLocation(next:string){setLocationId(next);submitKey.current=key("admin-inventory-count");await refresh(next);}
  async function submit(event:React.FormEvent){event.preventDefault();if(!context||observation.trim().length<4)return;const items=context.balances.map((item)=>({productId:item.productId,expectedOnHandQuantity:item.onHandQuantity,expectedReservedQuantity:item.reservedQuantity,countedOnHandQuantity:Number(values[item.productId])}));if(!items.length||items.some((item)=>!Number.isSafeInteger(item.countedOnHandQuantity)||item.countedOnHandQuantity<0))return;setAction("submit");try{const response=await fetch("/api/v1/inventory/counts",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":submitKey.current},body:JSON.stringify({locationId,observation:observation.trim(),items})});if(!response.ok)throw new Error(await responseMessage(response));if(!inventoryCountMutationResponseSchema.safeParse(await response.json()).success)throw new Error("A contagem retornou dados inválidos.");submitKey.current=key("admin-inventory-count");setObservation("");showToast("Contagem enviada para confirmação.","success");await refresh(locationId);}catch(cause){setError(messageFrom(cause));}finally{setAction(null);}}
  async function resolve(item:Count,decision:"APPROVE"|"REJECT"){const reason=decisionReasons[item.id]?.trim()??"";if(reason.length<4)return;const operation=`${item.id}:${decision}`;const idempotency=decisionKeys.current.get(operation)??key("inventory-count-decision");decisionKeys.current.set(operation,idempotency);setAction(operation);try{const response=await fetch(`/api/v1/admin/inventory/counts/${item.id}`,{method:"PATCH",headers:{"Content-Type":"application/json","Idempotency-Key":idempotency},body:JSON.stringify({action:decision,reason})});if(!response.ok)throw new Error(await responseMessage(response));const parsed=inventoryCountMutationResponseSchema.safeParse(await response.json());if(!parsed.success)throw new Error("A decisão retornou dados inválidos.");decisionKeys.current.delete(operation);showToast(decision==="APPROVE"?`${parsed.data.data.adjustmentCount??0} ajuste(s) aplicado(s).`:"Contagem recusada.","success");await refresh(locationId);}catch(cause){setError(messageFrom(cause));}finally{setAction(null);}}
  async function older(){if(!context?.nextCursor||action)return;setAction("older");try{const page=await load(locationId,context.nextCursor);setContext((current)=>current?{...current,nextCursor:page.nextCursor,counts:[...current.counts,...page.counts.filter((item)=>!current.counts.some((known)=>known.id===item.id))]}:page);}catch(cause){setError(messageFrom(cause));}finally{setAction(null);}}
  return <div className="space-y-6"><Card className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-bold">Inventário físico</h2><p className="mt-1 text-sm text-[var(--g-text-secondary)]">Conte uma localização ou confirme contagens pendentes. Mudanças após a contagem exigem nova conferência.</p></div><Button type="button" size="sm" variant="ghost" onClick={()=>void refresh(locationId)} disabled={loading||Boolean(action)}><RefreshCw className={`size-4 ${loading?"animate-spin":""}`}/> Atualizar</Button></div>{error&&<p role="alert" className="mt-4 rounded-lg bg-[var(--g-status-danger-soft)] p-3 text-sm text-[var(--g-status-danger-foreground)]">{error}</p>}<form aria-label="Registrar inventário físico" className="mt-5 space-y-4" onSubmit={submit}><Field id="inventory-count-location" label="Localização"><select id="inventory-count-location" className="g-input" value={locationId} onChange={(event)=>void changeLocation(event.target.value)} disabled={loading||Boolean(action)}>{context?.locations.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{context?.balances.map((item)=><Field key={item.productId} id={`admin-count-${item.productId}`} label={item.productName} description={`Esperado ${item.onHandQuantity}; reservado ${item.reservedQuantity}.`}><Input id={`admin-count-${item.productId}`} type="number" min={0} value={values[item.productId]??""} onChange={(event)=>{setValues((current)=>({...current,[item.productId]:event.target.value}));submitKey.current=key("admin-inventory-count");}} disabled={Boolean(action)}/></Field>)}</div><Field id="admin-count-observation" label="Observação"><Input id="admin-count-observation" minLength={4} maxLength={500} value={observation} onChange={(event)=>{setObservation(event.target.value);submitKey.current=key("admin-inventory-count");}} disabled={Boolean(action)}/></Field><Button type="submit" loading={action==="submit"} disabled={!context?.balances.length||observation.trim().length<4||Boolean(action)}><ClipboardCheck className="size-4"/> Enviar contagem</Button></form></Card>
    <section aria-label="Contagens registradas"><h2 className="mb-3 text-lg font-bold">Contagens registradas</h2><div className="space-y-3">{loading&&!context?<Card className="p-6"><p role="status" className="flex gap-2"><Loader2 className="size-5 animate-spin"/> Carregando contagens…</p></Card>:!context?.counts.length?<Card className="p-5 text-sm">Nenhuma contagem nesta localização.</Card>:context.counts.map((item)=><article key={item.id}><Card className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{item.locationName}</p><p className="mt-1 text-sm text-[var(--g-text-secondary)]">{item.observation}</p></div><Badge tone={item.status==="APPLIED"?"success":item.status==="PENDING_APPROVAL"?"warning":"neutral"}>{labels[item.status]}</Badge></div><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="text-xs text-[var(--g-text-muted)]"><th className="py-2">Produto</th><th className="py-2 text-right">Esperado</th><th className="py-2 text-right">Contado</th><th className="py-2 text-right">Diferença</th></tr></thead><tbody>{item.items.map((entry)=><tr key={entry.productId} className="border-t"><td className="py-2">{entry.productName}</td><td className="py-2 text-right tabular-nums">{entry.expectedOnHandQuantity}</td><td className="py-2 text-right tabular-nums">{entry.countedOnHandQuantity}</td><td className="py-2 text-right font-semibold tabular-nums">{entry.differenceQuantity>0?"+":""}{entry.differenceQuantity}</td></tr>)}</tbody></table></div>{item.decisionReason&&<p className="mt-2 text-sm"><span className="text-[var(--g-text-muted)]">Decisão:</span> {item.decisionReason}</p>}{item.status==="PENDING_APPROVAL"&&<div className="mt-4 border-t pt-4"><label htmlFor={`count-decision-${item.id}`} className="text-sm font-semibold">Motivo da decisão</label><Input id={`count-decision-${item.id}`} className="mt-2" minLength={4} maxLength={500} value={decisionReasons[item.id]??""} onChange={(event)=>setDecisionReasons((current)=>({...current,[item.id]:event.target.value}))} disabled={Boolean(action)}/><div className="mt-3 flex gap-2"><Button type="button" size="sm" onClick={()=>void resolve(item,"APPROVE")} loading={action===`${item.id}:APPROVE`} disabled={(decisionReasons[item.id]?.trim().length??0)<4||Boolean(action)}><Check className="size-4"/> Confirmar ajustes</Button><Button type="button" size="sm" variant="secondary" onClick={()=>void resolve(item,"REJECT")} loading={action===`${item.id}:REJECT`} disabled={(decisionReasons[item.id]?.trim().length??0)<4||Boolean(action)}><X className="size-4"/> Recusar</Button></div></div>}</Card></article>)}{context?.nextCursor&&<Button type="button" variant="secondary" className="w-full" onClick={()=>void older()} loading={action==="older"}>Carregar anteriores</Button>}</div></section>
  </div>;
}
