"use client";

import { saveQuantityPricePromotionResponseSchema, saveQuantityPricePromotionSchema, type QuantityPricePromotion } from "@germinatura/contracts";
import { Badge, Button, Card, Field, Input } from "@germinatura/ui";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useRef, useState } from "react";

type ProductOption={id:string;sku:string;name:string;active:boolean};
const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
function parseMoney(value:string){const match=value.trim().match(/^(\d{1,13})(?:[,.](\d{1,2}))?$/);if(!match)return null;const cents=Number(match[1])*100+Number((match[2]??"").padEnd(2,"0"));return Number.isSafeInteger(cents)?cents:null;}
function localInput(value:string|null){if(!value)return"";const date=new Date(value);const offset=date.getTimezoneOffset()*60000;return new Date(date.getTime()-offset).toISOString().slice(0,16);}
function optionalPositive(value:string){if(!value.trim())return null;const number=Number(value);return Number.isInteger(number)&&number>0?number:NaN;}

export function PromotionManagement({promotions,products,unavailable,after,next}:{promotions:QuantityPricePromotion[];products:ProductOption[];unavailable:boolean;after?:string;next?:string}){
  const[selected,setSelected]=useState<string|null>(null);const[notice,setNotice]=useState("");const[generation,setGeneration]=useState(0);const promotion=promotions.find((item)=>item.id===selected);
  return <div className="px-4 py-8 sm:px-6 lg:px-8 lg:py-10"><div className="mx-auto max-w-[var(--g-content-standard)] space-y-6">
    <header><p className="text-sm font-semibold text-[var(--g-brand-primary)]">Catálogo</p><h1 className="mt-1 text-3xl font-bold">Promoções por quantidade</h1><p className="mt-2 max-w-3xl text-[var(--g-text-secondary)]">Crie e inative regras como “2 por R$ 10”. A cotação e o checkout continuam calculando o preço no servidor.</p></header>
    {unavailable&&<div role="alert" className="rounded-[var(--g-radius-control)] bg-[var(--g-status-danger-soft)] p-4">Não foi possível consultar as promoções. Atualize a página antes de alterar regras.</div>}
    {!unavailable&&<div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(360px,0.8fr)]"><Card className="p-5"><h2 className="text-xl font-semibold">Regras cadastradas</h2><p className="mt-1 text-sm text-[var(--g-text-secondary)]">{promotions.length} nesta página · histórico preservado por revisão</p>{notice&&<p role="status" className="mt-4 text-[var(--g-status-success-foreground)]">{notice}</p>}
      {!promotions.length?<p className="mt-6 text-sm text-[var(--g-text-secondary)]">Nenhuma promoção cadastrada.</p>:<ul className="mt-4 divide-y divide-[var(--g-border-subtle)]">{promotions.map((item)=>{const unsupported=item.cumulative||item.globalRedemptionLimit!==null||item.perUserRedemptionLimit!==null;return <li key={item.id} className="py-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{item.name}</p><p className="text-sm text-[var(--g-text-secondary)]">{item.code} · {item.rule.groupQuantity} por {money.format(item.rule.groupPriceCents/100)} · prioridade {item.priority}</p><div className="mt-2 flex flex-wrap gap-2"><Badge tone={item.active?"success":"neutral"}>{item.active?"Ativa":"Inativa"}</Badge><Badge tone={item.publicable?"info":"neutral"}>{item.publicable?"Publicável":"Interna"}</Badge><Badge tone="neutral">rev. {item.revision}</Badge>{unsupported&&<Badge tone="warning">Aguarda limites transacionais</Badge>}</div></div><Button type="button" variant="secondary" disabled={unsupported} title={unsupported?"A edição será liberada com os limites transacionais":undefined} onClick={()=>{setSelected(item.id);setNotice("");}}>Editar</Button></div></li>;})}</ul>}
    </Card><PromotionForm key={`${promotion?.id??"new"}:${promotion?.revision??0}:${generation}`} promotion={promotion} products={products} onNew={()=>{setSelected(null);setNotice("");}} onSaved={()=>{setSelected(null);setGeneration((value)=>value+1);setNotice("Promoção salva com auditoria e nova revisão.");}}/></div>}
    <nav aria-label="Páginas de promoções" className="flex gap-4">{after&&<Link className="inline-flex min-h-11 items-center underline" href="/admin/promocoes">Primeira página</Link>}{next&&<Link className="inline-flex min-h-11 items-center underline" href={`/admin/promocoes?after=${next}`}>Próxima página</Link>}</nav>
  </div></div>;
}

function PromotionForm({promotion,products,onNew,onSaved}:{promotion?:QuantityPricePromotion;products:ProductOption[];onNew:()=>void;onSaved:()=>void}){
  const router=useRouter();const[code,setCode]=useState(promotion?.code??"");const[name,setName]=useState(promotion?.name??"");const[description,setDescription]=useState(promotion?.description??"");const[active,setActive]=useState(promotion?.active??false);const[publicable,setPublicable]=useState(promotion?.publicable??false);const[priority,setPriority]=useState(String(promotion?.priority??0));const[validFrom,setValidFrom]=useState(localInput(promotion?.validFrom??new Date().toISOString()));const[validTo,setValidTo]=useState(localInput(promotion?.validTo??null));const[selectedProducts,setSelectedProducts]=useState<string[]>(promotion?.productIds??[]);const[channels,setChannels]=useState<Array<"PORTAL"|"PDV"|"RESERVA">>(promotion?.channels??["PDV"]);const[groupQuantity,setGroupQuantity]=useState(String(promotion?.rule.groupQuantity??2));const[groupPrice,setGroupPrice]=useState(promotion?(promotion.rule.groupPriceCents/100).toFixed(2).replace(".",","):"");const[maxGroups,setMaxGroups]=useState(promotion?.rule.maxGroupsPerLine?.toString()??"");const[reason,setReason]=useState("");const[saving,setSaving]=useState(false);const[error,setError]=useState("");const key=useRef<string|null>(null);
  const changed=()=>{key.current=null;setError("");};
  const toggleProduct=(id:string,checked:boolean)=>{changed();setSelectedProducts((current)=>checked?[...current,id]:current.filter((value)=>value!==id));};
  const toggleChannel=(channel:"PORTAL"|"PDV"|"RESERVA",checked:boolean)=>{changed();setChannels((current)=>checked?[...current,channel]:current.filter((value)=>value!==channel));};
  async function submit(event:React.FormEvent){event.preventDefault();const price=parseMoney(groupPrice);const payload={id:promotion?.id??null,expectedRevision:promotion?.revision??null,code:code.trim().toUpperCase(),name,description:description.trim()||null,active,publicable,priority:Number(priority),cumulative:false,validFrom:new Date(validFrom).toISOString(),validTo:validTo?new Date(validTo).toISOString():null,globalRedemptionLimit:null,perUserRedemptionLimit:null,productIds:selectedProducts,channels,rule:{type:"QUANTIDADE_PRECO" as const,groupQuantity:Number(groupQuantity),groupPriceCents:price,maxGroupsPerLine:optionalPositive(maxGroups)},reason};const parsed=saveQuantityPricePromotionSchema.safeParse(payload);if(!parsed.success){setError("Confira código, vigência, produtos, canais, valores e motivo.");return;}key.current??=`promotion:${crypto.randomUUID()}`;setSaving(true);setError("");try{const response=await fetch("/api/v1/admin/promotions",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":key.current},body:JSON.stringify(parsed.data)});const body:unknown=await response.json();if(!response.ok)throw new Error(body&&typeof body==="object"&&"message" in body&&typeof body.message==="string"?body.message:"Não foi possível salvar a promoção.");saveQuantityPricePromotionResponseSchema.parse(body);onSaved();router.refresh();}catch(cause){setError(cause instanceof Error?cause.message:"Falha de conexão.");}finally{setSaving(false);}}
  return <Card className="p-5"><h2 className="text-xl font-semibold">{promotion?"Editar promoção":"Nova promoção"}</h2><p className="mt-1 text-sm text-[var(--g-text-secondary)]">Esta fatia aceita regras não cumulativas e sem limites de uso. Limites só serão habilitados junto da reserva transacional.</p><form aria-label={promotion?"Editar promoção":"Nova promoção"} onSubmit={submit} className="mt-5 space-y-4"><fieldset disabled={saving} className="space-y-4"><Field id="promotion-code" label="Código"><Input id="promotion-code" required maxLength={80} value={code} onChange={(event)=>{changed();setCode(event.target.value.toUpperCase());}}/></Field><Field id="promotion-name" label="Nome"><Input id="promotion-name" required maxLength={160} value={name} onChange={(event)=>{changed();setName(event.target.value);}}/></Field><Field id="promotion-description" label="Descrição (opcional)"><textarea id="promotion-description" maxLength={2000} value={description} onChange={(event)=>{changed();setDescription(event.target.value);}} className="min-h-24 w-full rounded-[var(--g-radius-control)] border border-[var(--g-border-default)] bg-white p-3"/></Field><div className="grid gap-4 sm:grid-cols-2"><Field id="promotion-priority" label="Prioridade"><Input id="promotion-priority" type="number" min={0} max={1000} required value={priority} onChange={(event)=>{changed();setPriority(event.target.value);}}/></Field><Field id="promotion-quantity" label="Quantidade do grupo"><Input id="promotion-quantity" type="number" min={2} required value={groupQuantity} onChange={(event)=>{changed();setGroupQuantity(event.target.value);}}/></Field><Field id="promotion-price" label="Preço do grupo (R$)"><Input id="promotion-price" inputMode="decimal" required placeholder="10,00" value={groupPrice} onChange={(event)=>{changed();setGroupPrice(event.target.value);}}/></Field><Field id="promotion-max-groups" label="Máximo de grupos por item (opcional)"><Input id="promotion-max-groups" type="number" min={1} value={maxGroups} onChange={(event)=>{changed();setMaxGroups(event.target.value);}}/></Field><Field id="promotion-from" label="Início"><Input id="promotion-from" type="datetime-local" required value={validFrom} onChange={(event)=>{changed();setValidFrom(event.target.value);}}/></Field><Field id="promotion-to" label="Fim (opcional)"><Input id="promotion-to" type="datetime-local" value={validTo} onChange={(event)=>{changed();setValidTo(event.target.value);}}/></Field></div>
    <fieldset><legend className="font-semibold">Canais</legend><div className="mt-2 flex flex-wrap gap-4">{(["PORTAL","PDV","RESERVA"] as const).map((channel)=><label key={channel} className="flex min-h-11 items-center gap-2"><input className="size-5" type="checkbox" checked={channels.includes(channel)} onChange={(event)=>toggleChannel(channel,event.target.checked)}/>{channel}</label>)}</div></fieldset>
    <fieldset><legend className="font-semibold">Produtos</legend><div className="mt-2 max-h-56 space-y-1 overflow-y-auto rounded-[var(--g-radius-control)] border border-[var(--g-border-default)] p-2">{products.map((product)=><label key={product.id} className="flex min-h-11 items-center gap-3 rounded px-2 hover:bg-[var(--g-surface-hover)]"><input className="size-5" type="checkbox" checked={selectedProducts.includes(product.id)} onChange={(event)=>toggleProduct(product.id,event.target.checked)}/><span>{product.name} · {product.sku}{!product.active?" · inativo":""}</span></label>)}</div></fieldset>
    <div className="flex flex-wrap gap-4"><label className="flex min-h-11 items-center gap-2"><input className="size-5" type="checkbox" checked={active} onChange={(event)=>{changed();setActive(event.target.checked);}}/>Ativa</label><label className="flex min-h-11 items-center gap-2"><input className="size-5" type="checkbox" checked={publicable} onChange={(event)=>{changed();setPublicable(event.target.checked);}}/>Publicável</label></div><Field id="promotion-reason" label="Motivo"><Input id="promotion-reason" required minLength={4} maxLength={500} value={reason} onChange={(event)=>{changed();setReason(event.target.value);}}/></Field><div className="flex flex-wrap gap-3"><Button type="submit" loading={saving}>Salvar promoção</Button>{promotion&&<Button type="button" variant="secondary" onClick={onNew}>Nova promoção</Button>}</div></fieldset>{error&&<p role="alert" className="text-sm text-[var(--g-status-danger-foreground)]">{error}</p>}</form></Card>;
}
