import { idempotencyKeySchema, reportStockLossSchema, stockLossMutationResponseSchema, stockLossQuerySchema } from "@germinatura/contracts";
import { createRequestId } from "@germinatura/observability";
import { NextResponse } from "next/server";
import { AuthorizationError, requirePermission } from "@/lib/auth";
import { createAuthenticatedSupabaseClient } from "@/lib/authenticated-supabase";
import { lossError, lossFail, lossHeaders, mapLossContext } from "./helpers";

export async function GET(request: Request) { const requestId=createRequestId(request.headers); try { await requirePermission("inventory.loss.own"); const parsed=stockLossQuerySchema.safeParse(Object.fromEntries(new URL(request.url).searchParams)); if(!parsed.success)return lossFail(requestId,"INVALID_LOSS_QUERY","Consulta de perdas inválida.",422); const client=await createAuthenticatedSupabaseClient(request); const{data,error}=await client.rpc("get_stock_losses",{p_cursor:parsed.data.cursor??null,p_limit:parsed.data.limit}); if(error)return lossError(requestId,error); const result=await mapLossContext(data,requestId,async(path)=>{const signed=await client.storage.from("stock-loss-photos").createSignedUrl(path,900);return signed.error?null:signed.data.signedUrl;}); if(!result.success)return lossFail(requestId,"INVENTORY_UNAVAILABLE","A consulta retornou dados inválidos.",503); return NextResponse.json(result.data,{headers:lossHeaders(requestId)}); } catch(error){if(error instanceof AuthorizationError)return lossFail(requestId,error.status===401?"UNAUTHENTICATED":"FORBIDDEN",error.message,error.status);return lossFail(requestId,"INVENTORY_UNAVAILABLE","Não foi possível carregar as perdas.",503);} }
export async function POST(request: Request) { const requestId=createRequestId(request.headers); try { await requirePermission("inventory.loss.own"); const key=idempotencyKeySchema.safeParse(request.headers.get("idempotency-key")); const parsed=reportStockLossSchema.safeParse(await request.json().catch(()=>null)); if(!key.success||!parsed.success)return lossFail(requestId,"INVALID_STOCK_LOSS","Confira produto, quantidade, motivo e observação.",422); const client=await createAuthenticatedSupabaseClient(request);const correlationId=crypto.randomUUID();const{data,error}=await client.rpc("report_stock_loss",{p_product_id:parsed.data.productId,p_quantity:parsed.data.quantity,p_reason:parsed.data.reason,p_observation:parsed.data.observation,p_photo_path:parsed.data.photoPath??null,p_idempotency_key:key.data,p_correlation_id:correlationId});if(error)return lossError(requestId,error);const result=stockLossMutationResponseSchema.safeParse({data:{reportId:data?.report_id,status:data?.status,movementId:data?.movement_id??null,correlationId:data?.correlation_id},request_id:requestId});if(!result.success)return lossFail(requestId,"INVENTORY_UNAVAILABLE","Não foi possível confirmar a perda.",503);return NextResponse.json(result.data,{status:201,headers:lossHeaders(requestId)});}catch(error){if(error instanceof AuthorizationError)return lossFail(requestId,error.status===401?"UNAUTHENTICATED":"FORBIDDEN",error.message,error.status);return lossFail(requestId,"INVENTORY_UNAVAILABLE","Não foi possível registrar a perda.",503);} }
