import { execFileSync } from "node:child_process";
import { randomUUID } from "node:crypto";
import { expect, it } from "vitest";
const LOCATION="50000000-0000-4000-8000-000000000002";const PRODUCT="33000000-0000-4000-8000-000000000001";
type Config={apiUrl:string;publishableKey:string};type Outcome={ok:true;data:Record<string,unknown>}|{ok:false;error:string};type Balance={on_hand_quantity:number;reserved_quantity:number;available_quantity:number};
function config():Config{const output=execFileSync(process.execPath,["tools/run-supabase.mjs","status","-o","env"],{encoding:"utf8"});const apiUrl=output.match(/^API_URL="?([^"\r\n]+)"?$/m)?.[1];const publishableKey=output.match(/^PUBLISHABLE_KEY="?([^"\r\n]+)"?$/m)?.[1];if(!apiUrl||!publishableKey||!/^https?:\/\/(127\.0\.0\.1|localhost)(:\d+)?$/.test(apiUrl))throw new Error("Supabase local indisponível.");return{apiUrl,publishableKey};}
async function login(local:Config,email:string,password:string){const response=await fetch(`${local.apiUrl}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:local.publishableKey,"Content-Type":"application/json"},body:JSON.stringify({email,password})});const body=await response.json() as{access_token?:string;message?:string};if(!response.ok||!body.access_token)throw new Error(body.message??"Falha de autenticação");return body.access_token;}
async function rpc(local:Config,token:string,name:string,parameters:Record<string,unknown>):Promise<Outcome>{const response=await fetch(`${local.apiUrl}/rest/v1/rpc/${name}`,{method:"POST",headers:{apikey:local.publishableKey,Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(parameters)});const body=await response.json() as Record<string,unknown>;return response.ok?{ok:true,data:body}:{ok:false,error:typeof body.message==="string"?body.message:String(response.status)};}
async function balance(local:Config,token:string):Promise<Balance>{const response=await fetch(`${local.apiUrl}/rest/v1/inventory_balances?select=on_hand_quantity,reserved_quantity,available_quantity&location_id=eq.${LOCATION}&product_id=eq.${PRODUCT}`,{headers:{apikey:local.publishableKey,Authorization:`Bearer ${token}`}});const rows=await response.json() as Balance[];return rows[0]??{on_hand_quantity:0,reserved_quantity:0,available_quantity:0};}
async function adjustTo(local:Config,admin:string,target:number){const current=await balance(local,admin);expect(current.reserved_quantity).toBe(0);if(current.on_hand_quantity!==target)expect(await rpc(local,admin,"adjust_stock",{p_location_id:LOCATION,p_product_id:PRODUCT,p_quantity_delta:target-current.on_hand_quantity,p_reason:"Preparar corrida de inventário",p_idempotency_key:`count-race-adjust:${randomUUID()}`,p_correlation_id:randomUUID()})).toMatchObject({ok:true});}

it("serializa aprovação do inventário sem perder movimento concorrente",async()=>{const local=config();const[admin,seller]=await Promise.all([login(local,"admin.teste@institutojef.org.br","Admin123!"),login(local,"vendedor.teste@institutojef.org.br","Vendedor123!")]);const original=await balance(local,admin);expect(original.reserved_quantity).toBe(0);await adjustTo(local,admin,1);const submitted=await rpc(local,seller,"submit_inventory_count",{p_location_id:LOCATION,p_items:[{product_id:PRODUCT,expected_on_hand_quantity:1,expected_reserved_quantity:0,counted_on_hand_quantity:0}],p_observation:"Contagem concorrente da última unidade",p_idempotency_key:`count-race-submit:${randomUUID()}`,p_correlation_id:randomUUID()});expect(submitted).toMatchObject({ok:true});const countId=String(submitted.ok?submitted.data.count_id:"");const raced=await Promise.all([rpc(local,admin,"resolve_inventory_count",{p_count_id:countId,p_action:"APPROVE",p_reason:"Confirmar contagem concorrente",p_idempotency_key:`count-race-approve:${randomUUID()}`,p_correlation_id:randomUUID()}),rpc(local,admin,"adjust_stock",{p_location_id:LOCATION,p_product_id:PRODUCT,p_quantity_delta:1,p_reason:"Entrada concorrente ao inventário",p_idempotency_key:`count-race-entry:${randomUUID()}`,p_correlation_id:randomUUID()})]);const current=await balance(local,admin);if(raced.every((result)=>result.ok)){expect(current.on_hand_quantity).toBe(1);}else{expect(raced).toContainEqual({ok:false,error:"INVENTORY_COUNT_STALE"});expect(current.on_hand_quantity).toBe(2);expect(await rpc(local,admin,"resolve_inventory_count",{p_count_id:countId,p_action:"REJECT",p_reason:"Refazer após movimento concorrente",p_idempotency_key:`count-race-reject:${randomUUID()}`,p_correlation_id:randomUUID()})).toMatchObject({ok:true});}await adjustTo(local,admin,original.on_hand_quantity);expect(await balance(local,admin)).toEqual(original);});
