import { execFileSync } from "node:child_process";
import { randomUUID } from "node:crypto";
import { expect, it } from "vitest";
const LOCATION="50000000-0000-4000-8000-000000000002";const PRODUCT="33000000-0000-4000-8000-000000000001";
type Config={apiUrl:string;publishableKey:string};type Outcome={ok:true;data:Record<string,unknown>}|{ok:false;error:string};type Balance={on_hand_quantity:number;reserved_quantity:number;available_quantity:number};
function config():Config{const output=execFileSync(process.execPath,["tools/run-supabase.mjs","status","-o","env"],{encoding:"utf8"});const apiUrl=output.match(/^API_URL="?([^"\r\n]+)"?$/m)?.[1];const publishableKey=output.match(/^PUBLISHABLE_KEY="?([^"\r\n]+)"?$/m)?.[1];if(!apiUrl||!publishableKey||!/^https?:\/\/(127\.0\.0\.1|localhost)(:\d+)?$/.test(apiUrl))throw new Error("Supabase local indisponível.");return{apiUrl,publishableKey};}
async function login(local:Config,email:string,password:string){const response=await fetch(`${local.apiUrl}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:local.publishableKey,"Content-Type":"application/json"},body:JSON.stringify({email,password})});const body=await response.json() as{access_token?:string;message?:string};if(!response.ok||!body.access_token)throw new Error(body.message??"Falha de autenticação");return body.access_token;}
async function rpc(local:Config,token:string,name:string,parameters:Record<string,unknown>):Promise<Outcome>{const response=await fetch(`${local.apiUrl}/rest/v1/rpc/${name}`,{method:"POST",headers:{apikey:local.publishableKey,Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(parameters)});const body=await response.json() as Record<string,unknown>;return response.ok?{ok:true,data:body}:{ok:false,error:typeof body.message==="string"?body.message:String(response.status)};}
async function balance(local:Config,token:string):Promise<Balance>{const response=await fetch(`${local.apiUrl}/rest/v1/inventory_balances?select=on_hand_quantity,reserved_quantity,available_quantity&location_id=eq.${LOCATION}&product_id=eq.${PRODUCT}`,{headers:{apikey:local.publishableKey,Authorization:`Bearer ${token}`}});const rows=await response.json() as Balance[];return rows[0]??{on_hand_quantity:0,reserved_quantity:0,available_quantity:0};}
async function adjustTo(local:Config,admin:string,target:number){const current=await balance(local,admin);expect(current.reserved_quantity).toBe(0);if(current.on_hand_quantity!==target)expect(await rpc(local,admin,"adjust_stock",{p_location_id:LOCATION,p_product_id:PRODUCT,p_quantity_delta:target-current.on_hand_quantity,p_reason:"Preparar corrida de perda",p_idempotency_key:`loss-race-adjust:${randomUUID()}`,p_correlation_id:randomUUID()})).toMatchObject({ok:true});}
it("serializa o registro de perda contra a reserva da última unidade",async()=>{const local=config();const[admin,seller]=await Promise.all([login(local,"admin.teste@institutojef.org.br","Admin123!"),login(local,"vendedor.teste@institutojef.org.br","Vendedor123!")]);const original=await balance(local,admin);expect(original.reserved_quantity).toBe(0);await adjustTo(local,admin,1);expect(await rpc(local,admin,"configure_stock_loss_threshold",{p_threshold:0,p_reason:"Configurar corrida concorrente",p_idempotency_key:`loss-race-settings:${randomUUID()}`,p_correlation_id:randomUUID()})).toMatchObject({ok:true});const reservationOrigin=`loss-race:${randomUUID()}`;const raced=await Promise.all([rpc(local,seller,"report_stock_loss",{p_product_id:PRODUCT,p_quantity:1,p_reason:"MISSING",p_observation:"Última unidade extraviada",p_photo_path:null,p_idempotency_key:`loss-race-report:${randomUUID()}`,p_correlation_id:randomUUID()}),rpc(local,admin,"reserve_stock",{p_location_id:LOCATION,p_items:[{product_id:PRODUCT,quantity:1}],p_origin_type:"integration_test",p_origin_id:reservationOrigin,p_idempotency_key:`loss-race-reserve:${randomUUID()}`,p_correlation_id:randomUUID()})]);expect(raced.filter((result)=>result.ok)).toHaveLength(1);expect(raced.filter((result)=>!result.ok)).toEqual([{ok:false,error:"STOCK_CONFLICT"}]);const winner=raced.find((result):result is Extract<Outcome,{ok:true}>=>result.ok)!;expect(await balance(local,admin)).toMatchObject({on_hand_quantity:1,reserved_quantity:1,available_quantity:0});if("report_id" in winner.data){expect(await rpc(local,seller,"resolve_stock_loss",{p_report_id:winner.data.report_id,p_action:"CANCEL",p_reason:"Limpar corrida concorrente",p_idempotency_key:`loss-race-cancel:${randomUUID()}`,p_correlation_id:randomUUID()})).toMatchObject({ok:true});}else{expect(await rpc(local,admin,"release_stock_reservation",{p_reservation_id:winner.data.reservation_id,p_idempotency_key:`loss-race-release:${randomUUID()}`,p_correlation_id:randomUUID()})).toMatchObject({ok:true});}expect(await rpc(local,admin,"configure_stock_loss_threshold",{p_threshold:null,p_reason:"Restaurar configuração conservadora",p_idempotency_key:`loss-race-settings-restore:${randomUUID()}`,p_correlation_id:randomUUID()})).toMatchObject({ok:true});await adjustTo(local,admin,original.on_hand_quantity);expect(await balance(local,admin)).toEqual(original);});
